name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24  # 修改为你的 Go 版本

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v2.3.0
          args: --out-format=github-actions --new
