name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.2.1

      - name: Run golangci-lint in all go.mod directories
        run: |
          find . -name 'go.mod' -exec dirname {} \; | while read dir; do
            echo "Linting $dir"
            cd "$dir"
            if [ -z "$(find . -name '*.go')" ]; then
              echo "No Go files in $dir, skipping."
              continue
            fi
            golangci-lint run || exit 1
            cd -
          done
